config/routes.rb
Rails.application.routes.draw do
  get 'stats', to: 'stats#index'
  get 'versions', to: 'versions#index'

  resources :users
  resources :events do
    get :cancel, on: :member
    post :preview, on: :collection, to: 'events#preview_create'
    patch :preview, on: :member
  end
  resources :moderations do
    resources :notes, only: %i[new create]
    patch :preview, on: :member
    get :validate, :refuse, on: :member
    put :accept, on: :member
  end
  resources :digests, only: %i[index show]
  resources :regions, only: %i[index]
  get 'tags/orgas', to: 'tags#orgas'
  resources :tags, only: %i[index show]
  resources :maps, only: %i[index show]
  resources :orgas do
    get :cancel, :validate, :refuse, on: :member
    put :accept, on: :member
  end

  get 'showevent.php', to: redirect { |_, req| "events/#{req.params[:id]}" }
  get 'listevents.php', to: redirect { |_, req| "events?#{req.query_string}" }
  get 'editevent.php', to: redirect(lambda do |_, req|
    "events/#{req.params[:id]}/edit?secret=#{req.params[:secret]}"
  end)
  get '(:format)listevents.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get 'event.php',
      to: redirect { |_, r| "events?#{r.query_string}" }
  get '(:format)event.php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }
  get '(:format).php',
      to: redirect { |_, r| "events.#{r.format.to_sym}?#{r.query_string}" }

  devise_for :users,
             path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'events#index'

end

app/controllers/tags_controller.rb
# Manage event and organisation tags
class TagsController < InheritedResources::Base
  has_scope :region, :locality, :daylimit
  has_scope :period, type: :hash, using: %i[year week]
  has_scope :tag, as: :id

  def index
    @tags = ActsAsTaggableOn::Tag.where('taggings_count > ?',
                                        Rails.configuration.cloud_threshold)
    if params[:term]
      # Used to autocomplete tags
      @tags = @tags.select(:id, :name, 'name AS label')
                   .where('name LIKE ?', "#{params[:term]}%")
    end

    respond_to do |format|
      format.html
      format.json { render json: @tags }
    end
  end

  def show
    @events_future = apply_scopes Event.moderated.future
    @events_past = apply_scopes Event.moderated.past

    respond_to do |format|
      format.html
      format.json { render json: @events_future + @events_past }
    end
  end

  def orgas
    @tags = organise_tags apply_scopes(Orga.moderated)

    respond_to do |format|
      format.html
      format.json { render json: @tags }
    end
  end

  private

  # Splits, groups, rejects the less used
  def organise_tags(tags)
    tags.where.not(tags: '').pluck(:tags).map(&:split).flatten
        .group_by { |i| i }
        .map { |k, v| [k, v.size] }
        .reject { |_k, v| v <= 3 }
        .sort { |t| -t[1] }
  end
end

app/helpers/tags_helper.rb
# Helper for the tags views
module TagsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/tags/_context.html.haml
-# Used in pages header, event.show and tag.show

- if tags.to_s.include? 'libre-en-fete'
  - if controller_name != 'tags' && %w[show edit].include?(action_name)
    = t '.link'
  %a(href='https://www.libre-en-fete.net')
    = image_tag 'lef.png', width: '180', height: '60', alt: 'Libre en Fête',
      style: 'vertical-align: middle'

- elsif tags.include? 'linux-presentation-day'
  - if controller_name != 'tags' && %w[show edit].include?(action_name)
    = t '.link'
  %a(href='http://www.linux-presentation-day.org')
    = image_tag 'linux-presentation-day.png', width: '150', height: '75',
      alt: 'Linux presentation day', style: 'vertical-align: middle'

- elsif action_name == 'index'
  %em.fa.fa-tag
  = params[:tag]

- if action_name == 'index'
  %a(href="?tag=")
    %em.fa.fa-times

app/views/tags/index.html.haml
%h2
  %em.fa.fa-tags
  = title t '.title'

- tag_cloud @tags.order(:name), %w[css1 css2 css3 css4] do |tag, css_class|
  = link_to tag.name, { action: :show, id: tag.name }, class: css_class

%p.info
  %em.fa.fa-info-circle
  = t '.threshold', threshold: Rails.configuration.cloud_threshold

app/views/tags/show.html.haml
= render partial: '/tags/context', locals: { tags: params[:id] }

%h2
  %em.fa.fa-tag
  = title params[:id]
  \-
  %em.fa.fa-forward
  = t '.count', count: @events_future.count

%aside
  %h2
    %em.fa.fa-link
    = t '.links'

  %ul.fa-ul
    %li
      = link_to tags_path, class: :back do
        %em.fa.fa-li.fa-arrow-left
        = Event.human_attribute_name :tags
    %li
      = link_to events_path tag: params[:id] do
        %em.fa.fa-li.fa-calendar
        Agenda
    %li
      = link_to events_path format: :rss, tag: params[:id] do
        %em.fa.fa-li.fa-rss
        RSS
    %li
      = link_to events_path format: :ics, tag: params[:id] do
        %em.fa.fa-li.fa-th-list
        iCal
    %li
      = link_to maps_path tag: params[:id] do
        %em.fa.fa-li.fa-map-marker
        OpenStreetMap
    %li
      = link_to maps_path format: :json, tag: params[:id] do
        %em.fa.fa-li.fa-dot-circle
        GeoJSON

- @events_future.order('start_time asc').each do |event|
  %article.event{ class: event.tag_list }
    %h3
      = link_to event do
        %em.city= event.city
        = event.title
    %p.full_address
      - if event.place_name.present?
        %span= event.place_name
      - if event.address.present?
        %span= event.address
    %p= display_date event
    .description
      = sanitize event.description,
        tags: %w[p h1 h2 h3 h4 br table tr th td ul ol li a strong b em i img sub sup span],
        attributes: %w[href src width height style title]

- if @events_past.any?
  %h2
    %em.fa.fa-backward
    = t '.past'
    \-
    = t '.count', count: @events_past.count
  %ul.fa-ul
    - @events_past.order('start_time desc').each do |event|
      %li.event{ class: event.tag_list }
        = link_to event do
          - if event.locality?
            %em.locality.fa-li.fa.fa-globe
          %em.city{ title: event.address }= event.city
          = event.title
        .date= display_date event